const menuToggle = document.querySelector('.menu-toggle');
const nav = document.querySelector('.site-nav');
menuToggle.addEventListener('click', () => { const open = nav.classList.toggle('is-open'); menuToggle.setAttribute('aria-expanded', String(open)); });
nav.querySelectorAll('a').forEach(link => link.addEventListener('click', () => { nav.classList.remove('is-open'); menuToggle.setAttribute('aria-expanded', 'false'); }));

const canvas = document.querySelector('#snakeCanvas');
const ctx = canvas.getContext('2d');
const scoreEl = document.querySelector('#score');
const highScoreEl = document.querySelector('#highScore');
const healthEl = document.querySelector('#health');
const levelEl = document.querySelector('#level');
const comboEl = document.querySelector('#combo');
const bossHealthEl = document.querySelector('#bossHealth');
const stateEl = document.querySelector('#gameState');
const messageEl = document.querySelector('#gameMessage');
const startButton = document.querySelector('#startButton');
const pauseButton = document.querySelector('#pauseButton');
const restartButton = document.querySelector('#restartButton');
const attackButton = document.querySelector('#attackButton');
const dashButton = document.querySelector('#dashButton');
const grid = 20;
const cols = canvas.width / grid;
const rows = canvas.height / grid;
let snake, food, enemies, powerUp, demon, direction, nextDirection, score, highScore, health, level, stage, combo, bossHealth, running, paused, gameOver, timer, tickCount, attackFlash, dashCooldown, invulnerable;

function loadHighScore() { try { return Number(localStorage.getItem('tororo-hero-high-score')) || 0; } catch { return 0; } }
function saveHighScore() { try { localStorage.setItem('tororo-hero-high-score', String(highScore)); } catch { /* storage is optional */ } }
function isOccupied(cell) { return snake.some(segment => segment.x === cell.x && segment.y === cell.y) || enemies.some(enemy => enemy.x === cell.x && enemy.y === cell.y) || (demon.x === cell.x && demon.y === cell.y); }
function randomCell() { let next; do { next = { x: 1 + Math.floor(Math.random() * (cols - 2)), y: 1 + Math.floor(Math.random() * (rows - 2)) }; } while (isOccupied(next)); return next; }
function resetGame() { clearInterval(timer); timer = null; snake = [{ x: 6, y: 9 }, { x: 5, y: 9 }, { x: 4, y: 9 }]; demon = { x: cols - 5, y: rows - 5 }; enemies = []; powerUp = null; score = 0; highScore = loadHighScore(); health = 3; level = 1; stage = 1; combo = 0; bossHealth = 10; running = false; paused = false; gameOver = false; tickCount = 0; attackFlash = 0; dashCooldown = 0; invulnerable = 0; spawnEnemy(); spawnEnemy(); food = randomCell(); updateHud(); draw(); }
function updateHud() { scoreEl.textContent = String(score).padStart(2, '0'); highScoreEl.textContent = String(highScore).padStart(2, '0'); healthEl.textContent = String(Math.max(0, health)).padStart(2, '0'); levelEl.textContent = String(level).padStart(2, '0'); comboEl.textContent = String(combo).padStart(2, '0'); bossHealthEl.textContent = String(Math.max(0, bossHealth)); stateEl.textContent = paused ? 'PAUSED' : (gameOver ? 'GAME OVER' : (bossHealth === 0 ? 'VICTORY' : (running ? 'RUNNING' : 'READY'))); pauseButton.textContent = paused ? 'RESUME' : 'PAUSE'; }
function draw() { ctx.fillStyle = '#07100d'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.strokeStyle = '#10271d'; for (let x = 0; x < cols; x++) { ctx.beginPath(); ctx.moveTo(x * grid, 0); ctx.lineTo(x * grid, canvas.height); ctx.stroke(); } for (let y = 0; y < rows; y++) { ctx.beginPath(); ctx.moveTo(0, y * grid); ctx.lineTo(canvas.width, y * grid); ctx.stroke(); } drawFood(); if (powerUp) drawPowerUp(); enemies.forEach(drawEnemy); drawDemon(); snake.forEach((segment, index) => drawHeroSegment(segment, index)); if (attackFlash > 0) { ctx.strokeStyle = '#d7ff8f'; ctx.lineWidth = 3; ctx.strokeRect(snake[0].x * grid - 5, snake[0].y * grid - 5, grid * 2 + 10, grid * 2 + 10); ctx.lineWidth = 1; } }
function drawFood() { ctx.fillStyle = '#ff6589'; ctx.shadowColor = '#ff6589'; ctx.shadowBlur = 16; ctx.beginPath(); ctx.moveTo(food.x * grid + 10, food.y * grid + 3); ctx.lineTo(food.x * grid + 17, food.y * grid + 10); ctx.lineTo(food.x * grid + 10, food.y * grid + 17); ctx.lineTo(food.x * grid + 3, food.y * grid + 10); ctx.closePath(); ctx.fill(); ctx.shadowBlur = 0; }
function drawPowerUp() { ctx.fillStyle = powerUp.type === 'heal' ? '#4de3c1' : '#ffd166'; ctx.shadowColor = ctx.fillStyle; ctx.shadowBlur = 14; ctx.beginPath(); ctx.arc(powerUp.x * grid + 10, powerUp.y * grid + 10, 7, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; }
function drawHeroSegment(segment, index) { const x = segment.x * grid + 10; const y = segment.y * grid + 10; ctx.fillStyle = index === 0 ? '#d7ff8f' : '#64d99c'; ctx.beginPath(); ctx.arc(x, y, index === 0 ? 8 : 7, 0, Math.PI * 2); ctx.fill(); if (index === 0) { ctx.fillStyle = '#1b4b38'; ctx.fillRect(x - 5, y - 10, 10, 5); ctx.fillStyle = '#07100d'; ctx.fillRect(x - 4, y - 2, 3, 3); ctx.fillRect(x + 2, y - 2, 3, 3); } }
function drawEnemy(enemy) { const x = enemy.x * grid + 10; const y = enemy.y * grid + 10; ctx.fillStyle = '#ef476f'; ctx.fillRect(x - 7, y - 7, 14, 14); ctx.fillStyle = '#07100d'; ctx.fillRect(x - 4, y - 2, 3, 3); ctx.fillRect(x + 2, y - 2, 3, 3); }
function drawDemon() { const x = demon.x * grid + 10; const y = demon.y * grid + 10; ctx.fillStyle = '#bb557d'; ctx.beginPath(); ctx.moveTo(x - 10, y + 8); ctx.lineTo(x - 7, y - 8); ctx.lineTo(x - 2, y - 12); ctx.lineTo(x + 2, y - 12); ctx.lineTo(x + 7, y - 8); ctx.lineTo(x + 10, y + 8); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#ffcedb'; ctx.fillRect(x - 5, y - 2, 3, 3); ctx.fillRect(x + 2, y - 2, 3, 3); }
function spawnEnemy() { enemies.push(randomCell()); }
function setDirection(name) { const next = { up: { x: 0, y: -1, name }, down: { x: 0, y: 1, name }, left: { x: -1, y: 0, name }, right: { x: 1, y: 0, name } }[name]; const opposite = direction && next && next.x === -direction.x && next.y === -direction.y; if (next && !opposite) nextDirection = next; }
function growSnake() { snake.push({ ...snake[snake.length - 1] }); }
function moveSnake() { direction = nextDirection; const head = { x: snake[0].x + direction.x, y: snake[0].y + direction.y }; const hitWall = head.x < 0 || head.x >= cols || head.y < 0 || head.y >= rows; const hitSelf = snake.some(segment => segment.x === head.x && segment.y === head.y); if (hitWall || hitSelf) return endGame('GAME OVER: 던전의 벽에 부딪혔습니다.'); snake.unshift(head); const ateFood = head.x === food.x && head.y === food.y; if (ateFood) collectFood(); else snake.pop(); if (powerUp && head.x === powerUp.x && head.y === powerUp.y) collectPowerUp(); if (enemies.some(enemy => enemy.x === head.x && enemy.y === head.y)) takeDamage(); updateHud(); draw(); }
function collectFood() { score += 1; combo += 1; growSnake(); food = randomCell(); if (score > highScore) { highScore = score; saveHighScore(); } level = 1 + Math.floor(score / 5); stage = level; bossHealth = Math.max(0, bossHealth - 1); if (score % 4 === 0) powerUp = { ...randomCell(), type: score % 8 === 0 ? 'rage' : 'heal' }; if (score % 3 === 0 && enemies.length < 2 + level) spawnEnemy(); messageEl.textContent = `룬 획득! 레벨 ${level}, 콤보 ${combo}.`; if (bossHealth === 0) endGame('VICTORY: 성장한 용사가 마왕의 결계를 무너뜨렸습니다.', true); }
function collectPowerUp() { if (!powerUp) return; if (powerUp.type === 'heal') health = Math.min(5, health + 1); else bossHealth = Math.max(0, bossHealth - 2); messageEl.textContent = powerUp.type === 'heal' ? '회복의 빛! 체력이 회복되었습니다.' : '분노의 룬! 마왕에게 큰 피해를 입혔습니다.'; powerUp = null; }
function moveEnemies() { enemies.forEach(enemy => { const horizontal = Math.abs(snake[0].x - enemy.x) >= Math.abs(snake[0].y - enemy.y); if (horizontal) enemy.x += Math.sign(snake[0].x - enemy.x); else enemy.y += Math.sign(snake[0].y - enemy.y); enemy.x = Math.max(1, Math.min(cols - 2, enemy.x)); enemy.y = Math.max(1, Math.min(rows - 2, enemy.y)); }); if (enemies.some(enemy => enemy.x === snake[0].x && enemy.y === snake[0].y)) takeDamage(); }
function moveDemon() { if (tickCount % 3 !== 0) return; if (Math.abs(snake[0].x - demon.x) > Math.abs(snake[0].y - demon.y)) demon.x += Math.sign(snake[0].x - demon.x); else demon.y += Math.sign(snake[0].y - demon.y); demon.x = Math.max(2, Math.min(cols - 3, demon.x)); demon.y = Math.max(2, Math.min(rows - 3, demon.y)); if (demon.x === snake[0].x && demon.y === snake[0].y) takeDamage(); }
function takeDamage() { if (invulnerable > 0) return; health -= 1; combo = 0; invulnerable = 8; snake = snake.slice(0, 3); messageEl.textContent = `피격! 남은 체력 ${health}.`; if (health <= 0) endGame('GAME OVER: 용사의 체력이 모두 소진되었습니다.'); }
function attack() { if (!running || paused || gameOver) return; attackFlash = 2; const distance = Math.abs(snake[0].x - demon.x) + Math.abs(snake[0].y - demon.y); if (distance <= 3 && score >= 2) { const damage = 1 + Math.floor(combo / 4); bossHealth = Math.max(0, bossHealth - damage); combo += 1; messageEl.textContent = bossHealth ? `검격 성공! ${damage} 피해, 마왕 HP ${bossHealth}.` : 'VICTORY: 검격으로 마왕을 물리쳤습니다.'; if (bossHealth === 0) return endGame(messageEl.textContent, true); } else messageEl.textContent = '룬을 2개 이상 모으고 마왕에게 가까이 가세요.'; updateHud(); draw(); }
function dash() { if (!running || paused || gameOver) return; if (dashCooldown > 0) return; const destination = { x: Math.max(1, Math.min(cols - 2, snake[0].x + direction.x * 3)), y: Math.max(1, Math.min(rows - 2, snake[0].y + direction.y * 3)) }; snake[0] = destination; dashCooldown = 18; invulnerable = 5; messageEl.textContent = '대시 성공! 잠시 무적입니다.'; draw(); }
function tick() { if (!running || paused || gameOver) return; tickCount += 1; attackFlash = Math.max(0, attackFlash - 1); dashCooldown = Math.max(0, dashCooldown - 1); invulnerable = Math.max(0, invulnerable - 1); moveSnake(); if (gameOver) return; if (tickCount % Math.max(2, 5 - level) === 0) moveEnemies(); moveDemon(); updateHud(); draw(); }
function endGame(message, victory = false) { clearInterval(timer); timer = null; running = false; gameOver = !victory; if (victory) bossHealth = 0; updateHud(); messageEl.textContent = message; startButton.textContent = victory ? 'PLAY AGAIN ↗' : 'RETRY ↗'; draw(); }
function startGame() { resetGame(); running = true; startButton.textContent = 'RUNNING ↗'; messageEl.textContent = '룬을 먹고 적을 피하며 마왕에게 접근하세요.'; updateHud(); timer = setInterval(tick, 140); }
function togglePause() { if (!running || gameOver) return; paused = !paused; messageEl.textContent = paused ? '일시정지 중입니다.' : '다시 던전으로 진입합니다.'; updateHud(); draw(); }
function restartGame() { startGame(); }
document.addEventListener('keydown', event => { const keys = { ArrowUp: 'up', w: 'up', W: 'up', ArrowDown: 'down', s: 'down', S: 'down', ArrowLeft: 'left', a: 'left', A: 'left', ArrowRight: 'right', d: 'right', D: 'right' }; if (keys[event.key]) { event.preventDefault(); setDirection(keys[event.key]); } if (event.code === 'Space') { event.preventDefault(); attack(); } if (event.key === 'Shift') { event.preventDefault(); dash(); } if (event.key === 'p' || event.key === 'P') { event.preventDefault(); togglePause(); } });
document.querySelectorAll('[data-direction]').forEach(button => button.addEventListener('click', () => setDirection(button.dataset.direction)));
attackButton.addEventListener('click', attack); dashButton.addEventListener('click', dash); startButton.addEventListener('click', startGame); pauseButton.addEventListener('click', togglePause); restartButton.addEventListener('click', restartGame);
let touchStart = null;
canvas.addEventListener('touchstart', event => { touchStart = event.changedTouches[0]; }, { passive: true });
canvas.addEventListener('touchend', event => { if (!touchStart) return; const touch = event.changedTouches[0]; const dx = touch.clientX - touchStart.clientX; const dy = touch.clientY - touchStart.clientY; if (Math.max(Math.abs(dx), Math.abs(dy)) > 20) setDirection(Math.abs(dx) > Math.abs(dy) ? (dx > 0 ? 'right' : 'left') : (dy > 0 ? 'down' : 'up')); touchStart = null; }, { passive: true });
resetGame();
